### ISSUE TITLE
Incorrect processing of a batch response for GET methods

### ISSUE THREAD

**Issue by angfal** [thorning/node-mailchimp#12]
Hi Andreas,

If create a batch request which contains several GET methods, MC returns an archive with several json files. The current batch implementation expects only one file, as the result, the batch function returns incorrect response

Thank you for your job!

**Comment by thorning** [comment]
I think this is related to #10 . I wrote to mailchimp on the issue, but did not hear back.

It seems that if you capitalize the methods, the return will be several json files, which this library currently does not handle. If out lower case them, it have worked as expected so far for me.

I believe this is an error on mailchimps end, since the operations count in the batch status is also wrong when using capitalized methods.

I will look into making this library handle both cases though

**Comment by angfal** [comment]
Year, I low cased my methods and it works as expected. Very interesting "feature" on the Mailchimp size. 

Thanks a lot, you a very help!

**Comment by thorning** [comment]
I have just updated the module to handle both cases. I now force uppercase on the methods, as that seems to be what mailchimp expects according to #10 , and then handle the split results.

**Comment by angfal** [comment]
Tried the new version, looks great! Thanks a lot!
