### ISSUE TITLE
Why are batch requests so slow?

### ISSUE THREAD

**Issue by IonicaBizau** [thorning/node-mailchimp#25]
I have the feeling that the batch requests are very very slow.

Are they slow because they're making a lot of requests in the background (not more than 10 in parallel) or is there is some other reason for it?

I can see in my terminal something like this:

![screen shot 2017-04-26 at 11 12 59](https://cloud.githubusercontent.com/assets/2864371/25424550/5b54fc06-2a71-11e7-9b05-cba413f432ad.png)

How do these work and how to make them faster?

Thanks!

**Comment by thorning** [comment]
They are slow because they are queued on mailchimps servers.

The following is my speculations, but as I dont work for mailchimp it might not be true:
- Mailchimp might throttle you, if you send alot of batch operations
- Mailchimp might throttle you more often if you are on a free account
- Mailchimp might throttle multiple concurrent batch operations on the same account

I made this library to be able to write scripts to transparently handle the batch operations, but the batching and wait will always be there.

One feature that I did not add yet, as I have not needed it yet, is transparent resuming of batches. 

This could potentially make sense for very large jobs

**Comment by IonicaBizau** [comment]
I didn't look yet at the code, but are the batch requests used for pagination?

From what I know Mailchimp allows us to do 10 requests in parallel.

**Comment by thorning** [comment]
the batch is a simple wrapper around mailchimp batch requests [http://developer.mailchimp.com/documentation/mailchimp/reference/batches/](http://developer.mailchimp.com/documentation/mailchimp/reference/batches/).

The library does not make the calls directly. It makes one batch call to mailchimp, awaits the completion, and unwraps the results, so the flow looks like a normal mailchimp api call.

If all you need it to make a few normal api calls, chances are you should just call i.e. `mailchimp,get()`. You can manually do several of these in parallel using your favorite control flow (Promises.all or async most likely)
