### ISSUE TITLE
mailchimp API GET lists/listid/members/emailhash does not return 404 instead errors with 404

### ISSUE THREAD

**Issue by Jaikant** [thorning/node-mailchimp#33]
The mailchimp API GET lists/listid/members/emailhash does not return 404 instead errors with 404.

This seems like a clumsy behaviour within the mailchimp API, just wondering if folks here are seeing the same behaviour. My worry is if this behaviour changes in the future it would break existing implementations.

I am adding subscribers using the below logic.
1. check if user is on list.
2. If return is successful with statusCode of 200, then do not add user to the list
3. If statusCode is 404 add user to list.

But the behaviour I am seeing is if user is not in the list, the "GET" errors with a 404. So I need to catch the error and then add the user to the list. This does not seem alright. Should not the GET instead succeed with a statusCode of 404.

```
 mailchimp.get(`lists/listid/members/${emailhash}`)
      .then(function(results) {
        if (results.statusCode == 200) {
        } else if (results.statusCode == 404) {
          //**The mailchimp api does not come here**

          mailchimp.post('/lists/listid/members', {
            email_address : toemail,
            status : 'subscribed'
          })
        }
      })
      .catch(function (err) {

        //**In the current mailchimp API, an error is returned with 404 if email is not subscribed.**

        if (err.status == 404) {

          mailchimp.post('/lists/listid/members', {
            email_address : toemail,
            status : 'subscribed'
          }) 
       }
      })
```

**Comment by thorning** [comment]
This is currently the expected behavior. I don't have any plans to change this, but if I do, I will bump the major version as it would indeed be a breaking change.

Currently the design is that non-2xx responses are errors, and should handled as such. This mirror other popular promise based request libraries such as [axios](https://github.com/axios/axios).

I think the reasoning behind this design, is that most use cases expect a 2xx response, and it would be annoying to make explicit checks after each request (and error prone not to). 
 
In this particular case I think you could just make the post request directly to add a member, and I think you should get an error if the email already exists. (test it though, I take no responsibilities :)).

If you need to do this for many members at once, you can use the batch api for that.
