### ISSUE TITLE
Mailchimp is not a constructor

### ISSUE THREAD

**Issue by Osovich** [thorning/node-mailchimp#58]
Hi, im trying to use this package but "var mailchimp = new Mailchimp(api_key);" returns me "Mailchimp is not a constructor", am I doing something wrong?

**Comment by Osovich** [comment]
if i only use the var Mailchimp = require('mailchimp-api-v3') line, i get a process binding is not supported, am i doing something wrong?

**Comment by thorning** [comment]
If you are using typescript you need to import the module something like:
`import Mailchimp = require('mailchimp-api-v3');`

If this does not help, I will need more info, including your environment, before there is a chance I can help.

**Comment by ianbytchek** [comment]
@thorning You might want to add `declare namespace Mailchimp {}` to d.ts file for TypeScript to support ES6 target, see [example](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html). Otherwise, imports like:
```ts
import * as Mailchimp from "mailchimp-api-v3";
``` 
Fail with error: `TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.` Note, using `esModuleInterop` solves this issue, but might cause other problems.

I'm not super-experience on this specific subject,  but the commented out `export as namespace mailchimpApiV3` used to do the same thing, but, I believe, was deprecated – again, might be not 100% accurate, but something like this comes up in my memory.

**Comment by thorning** [comment]
I am a bit hesitant to change the typings - last time I got quite a few reports of broken builds etc.

The best solution would be to rewrite the module in Typescript, and would properly be fairly fast to do.. But I don't have to time currently to do so

**Comment by rscotten** [comment]
This works:

```typescript
// @ts-ignore
import * as Mailchimp from 'mailchimp-api-v3';
```
